### PR TITLE
Hey Troy this is Andon its pretty gud just accept it

### PR DESCRIPTION
**Pull request by UrCousinErnesto**
* Fixed Issue with multiples of same car showing up in image
* Fixed spelling mistake in heading for "research new cars"

### CODE REVIEW

**Comment by destinyshi** [comment]
its emma blando

**Comment by bannaturt** [comment]
thx man thats pretty nice and who's emma

**Comment by bannaturt** [comment]
thx man
that pretty nice

**Comment by kylesureline** [comment]
Don't listen to the haters Andon 👍 👍 👍

**Comment by destinyshi** [comment]
LISTEN TO THE HATERS ANDON 👎 👎 👎 👎

**Comment by IceChicken444** [comment]
**_# BRAGLEGBTNGHYUDHTMSKC!!!_**

**Comment by SpoopedBob** [comment]
Andon is a gud man

**Comment by DukeSucks** [comment]
Big Shaq

**Comment by Foxtro7** [comment]
The one and only

**Comment by SpoopedBob** [comment]
Mans not hot

**Pull request closed without merging**
